[package]
edition = "2018"
name = "advent-of-code"
version = "0.1.0"
authors = ["Austin Krill <akrill91@gmail.com>"]

[dependencies]
env_logger = "0.11"
itertools = "0.13"
log = "0.4"
petgraph = "0.8.3"
regex = "1.11"
tokio = { version = "1", features = ["full"] }